# Generated by Django 3.2.9 on 2021-11-16 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, null=True, verbose_name='Message ID')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Email Address')),
                ('from_user', models.CharField(max_length=255, null=True, verbose_name='From')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='Subject')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 16, 12, 50, 35, 51708))),
                ('payload', models.TextField(null=True, verbose_name='Payload')),
                ('visual', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=255, null=True, verbose_name='Email Password')),
                ('proxy_url', models.CharField(max_length=255, verbose_name='Proxy URL')),
                ('count_messages', models.IntegerField(null=True, verbose_name='Count messages')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 11, 16, 12, 50, 35, 51708))),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
    ]
