version: "3.9"

services:
  web:
    restart: always
    build: .
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    #  - redis

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  celery_worker:
    restart: always
    build:
      context: .
    command: "celery --app FuckMail worker -l INFO --pool=solo"
    volumes:
      - ./FuckMail:/FuckMail
    depends_on:
      - redis
      - web

  celery_beat:
    restart: always
    build:
      context: .
    command: "celery -A FuckMail beat -l INFO"
    volumes:
      - ./FuckMail:/FuckMail
    depends_on:
      - redis
      - web